# Generated by Django 5.1.7 on 2025-03-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeevaluation',
            options={'verbose_name': 'Store Evaluation', 'verbose_name_plural': 'Store Evaluations'},
        ),
        migrations.AlterModelOptions(
            name='storeinformation',
            options={'verbose_name': 'Store Information', 'verbose_name_plural': 'Stores Information'},
        ),
        migrations.AlterField(
            model_name='storeevaluation',
            name='cleanliness',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='storeevaluation',
            name='customer_service',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='storeevaluation',
            name='efficiency',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='storeevaluation',
            name='standard_spiel',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='storeinformation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
