# Generated by Django 5.1.7 on 2025-04-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_storeevaluation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinformation',
            name='category',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Food & Beverage', 'Food & Beverage'), ('Service-Based', 'Service-Based'), ('Gas Station', 'Gas Station'), ('Other', 'Other')], default='Retail', max_length=50),
        ),
        migrations.AddField(
            model_name='storeinformation',
            name='custom_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeinformation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
