# Generated by Django 5.1.7 on 2025-04-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_alter_storeevaluation_evaluation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeevaluation',
            name='ac1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='ac2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='ac3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='ce1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='ce2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='ce3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='ce4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='ce5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='ce6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cl1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cl2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cl3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cl4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cl5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cl6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cl7_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cn10_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cn11_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cn1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cn2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cn3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cn4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cn5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cn6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cn7_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cn8_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='cn9_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='pg1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='pq1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='pq2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='ss1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='ss2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeevaluation',
            name='ss3_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
