# Generated by Django 5.1.7 on 2025-04-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_remove_storeevaluation_ac1_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeevaluation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
